<a href="https://colab.research.google.com/github/ShikhartheDeveloper/Python-Learning-Journey/blob/main/Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [ ]:
a = np.array([1,2])
b = np.array([3,4])
print(a + b)
print(3 * a)

[4 6]
[3 6]


3 dot a is makes the point of a 3x times at same direction

now make the 2, 3 dimensional vector and find the dot product

In [ ]:
c = np.array([1,2,3])
d = np.array([4,5,6])

print(np.dot(c,d))

32


the dot product formula is :-
a . b = a1b1 + a2b2 + ...... + anbn

In [ ]:
print("mze")

mze


** Norm 2 Euclidean lenght**
firstly do the square of all values in vector then add  them and then square it

||v2|| = √(v1**2 + v2**2 + ..... + Vn**2)

In [ ]:
z = np.array([1,2,2])
print(np.linalg.norm(z))

# if we find the euclidean distance from 2 points then

h = np.array([2,3])
i = np.array([4,5])
print(np.linalg.norm(i -h))

3.0
2.8284271247461903


***Norm 1 (MANHATTAN DISTANCE) :-    here is not taking the square and square root too***

*||v|| = |v1| + |v2| + .... + |vn|*

if there is any  negative values so it turns to absolute value like -7 => 7

In [ ]:
a = np.array([3,4,-2])    # -2 positive hojayga = 2
print(np.linalg.norm(a, ord=1))

9.0


***Norm ∞ (Max/ infinity norm) :-    here is not taking the square and square root too but here find the max value (absoulute) from vectors***

||v||∞ = max(|v1|,|v2|,.......,|vn|)

In [ ]:
k = np.array([4,-9,7])  # -9 turns absolute becomes 9
print(np.linalg.norm(k, ord=np.inf))

9.0


In [ ]:
a = np.array([1,2])
b = np.array([2,4])
cos_sim = np.dot(a,b) / (np.linalg.norm(a) * np.linalg.norm(b))
print(cos_sim)

0.9999999999999998


**How to declare a matrix**

In [6]:
a = np.array([[1,2,3],
              [4,5,6]])
print(a.shape)

(2, 3)


A = [[1,2,3],
      [4,5,6]]    

**Transpose**

Aᵗ = [[1,4],
      [2,5],
      [3,6]]        

 rows become columns and columns become rows

In [8]:
B = np.array([[1,2,3],
             [4,5,6]])
print(B.T)    # T use for Transpose

[[1 4]
 [2 5]
 [3 6]]


In [14]:
# addition of matrices
l = np.array([[1,2],[3,4]])
m = np.array([[5,6],[7,8]])
print(l+m)


[[ 6  8]
 [10 12]]


In [16]:
# multiplication of array

k = np.array([[1,2] , [3,4]])
print(3 * k)

[[ 3  6]
 [ 9 12]]


**Special metrices**


In [17]:
# identity matrices (basic)
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
# zero matrices
Z = np.zeros((3,3))
print(Z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [24]:
# diagonal matrix
D = np.diag([5,7,3])
print(D)
print()
# if find the diagonal then
M = np.array([[1,2],[3,4]])
print(np.diag(M))

[[5 0 0]
 [0 7 0]
 [0 0 3]]

[1 4]
