In [2]:
#np.array
import numpy as np
a = np.array([1,2,3])
# also called 1-d array or vector
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
#2d array

b = np.array([[1,2,3],[4,5,6]])
# this is 2-d array or matrix
print(b)
print(b.ndim)

[[1 2 3]
 [4 5 6]]
2


In [4]:
# 3d array or tensor

c = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])
print(c)
print(c.ndim)    #identify the array size

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


In [5]:
# dtype -> you can make array with your datatype like float
np.array([1,2,3],dtype='float')

# bool
np.array([5,6,7],dtype='bool')

array([ True,  True,  True])

In [6]:
# np.arange is used to create the array with like range function (1,11)
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
#np.reshape
# with reshape , it can change the shape of your array takes 2 parameter (rows,cols)
f = np.arange(8).reshape(2,2,2)
print(f)
print(f.ndim)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
3


In [8]:
# np.ones 
# create the rows colums value by ones when you pass it in tuple
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
# np.zeros 
# create the rows colums value by zeros when you pass it in tuple

np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
# np.random
# np.random create random values for array between zero 0 to 1 ones
np.random.random((6,4))

array([[0.60305243, 0.49997226, 0.4359028 , 0.69484516],
       [0.38586893, 0.07001339, 0.76137896, 0.37826884],
       [0.23642434, 0.23846626, 0.16546077, 0.54426176],
       [0.05734363, 0.48815589, 0.21605249, 0.64031044],
       [0.63883526, 0.26192882, 0.93515368, 0.57969002],
       [0.20717236, 0.77136538, 0.90184557, 0.36502869]])

In [11]:
# np.linspace - > linear space 
# linspace creates an array of evenly spaced numbers between a start and end value.
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [12]:
# np.identity() — Identity Matrix
# np.identity(n) creates a square matrix of size n x n with 1s on the diagonal and 0s everywhere else.

np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
##* Array Attributes

In [14]:
a1 = np.arange(10)
a2 = np.arange(12,dtype='float').reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [15]:
# .ndim -> number of dimensions , its an attribute of numpy 
a1.ndim

1

In [16]:
# .shape
# .shape tells you the size of an array along each dimension — it's a tuple showing how many elements exist in each axis.
a2.shape

(3, 4)

In [17]:
# .size
# .size tells you the total number of elements in an array — regardless of how many dimensions it has.
a2.size

12

In [18]:
# .itemsize in NumPy
# .itemsize tells you the number of bytes used to store a single element in the array.
a2.itemsize

8

In [19]:
# .dtype in NumPy
# .dtype tells you the data type f the elements stored in the array — i.e., what kind of values it holds 
# (integers, floats, booleans, strings, etc.) and how they're stored in memory.

a1.dtype
a2.dtype

dtype('float64')

In [20]:
# Changing Datatype 

# .astype() in NumPy
# .astype() converts an array's data type into a new one — it creates a new array with the converted values (the original array is not changed).

a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [21]:
## Array operations

In [22]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [23]:
# Scalar operations
# arithmetic
a1 * 2 # where 2 is scalar

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [24]:
# Relational Operator
# like if we compare the a2 with >13 so check it now

a2 > 13  # check one by one value and compare it
a2 == 15  # where it find the 15 making true , else false everywhere

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [25]:
# vector operations -> because it will do between 2 arrays that's why we are calling it vector operations
# arithmetic

a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [26]:
# Array Functions

In [27]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[42.,  6., 41.],
       [37., 27., 10.],
       [35., 98., 30.]])

In [28]:
print(np.sum(a1))
# gives you the max element present in the array   max/min/sum/prod
print(np.max(a1))
print(np.min(a1))
# np.prod() multiplies all elements in the array together and returns a single number (the product).
print(np.prod(a1))

326.0
98.0
6.0
10620996372000.0


In [29]:
# if we want to get  Max of Every Column → axis=0
# if we want to get  Max of Every Row → axis=1
print(a1)
print(np.max(a1,axis=0))
print(np.max(a1,axis=1))

[[42.  6. 41.]
 [37. 27. 10.]
 [35. 98. 30.]]
[42. 98. 41.]
[42. 37. 98.]


In [30]:
# mean/median/std/var
# mean -> Average [1,2,3,4,5] sum = 15 , total number = 5 so mean is 15/5 = 3
np.mean(a1)

# np.median() finds the middle value of a sorted array — it's less affected by extreme outliers than np.mean().
np.median(a1)

# .std() / np.std() — Standard Deviation

# std measures how spread out the values in an array are from the mean. A low std means values are close to the average; 
# a high std means they're spread far apart.
np.std(a1)

# .var() / np.var() — Variance

# var measures how spread out values are from the mean — same idea as std, but without the final square root step.
#     It's the "average squared distance from the mean."

np.var(a1)

np.float64(622.1728395061729)

In [31]:
# trigonometric functions
np.sin(a1)

array([[-0.91652155, -0.2794155 , -0.15862267],
       [-0.64353813,  0.95637593, -0.54402111],
       [-0.42818267, -0.57338187, -0.98803162]])

In [32]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [33]:
# log and exponent
print(np.log(a1))
print(np.exp(a1))

[[3.73766962 1.79175947 3.71357207]
 [3.61091791 3.29583687 2.30258509]
 [3.55534806 4.58496748 3.40119738]]
[[1.73927494e+18 4.03428793e+02 6.39843494e+17]
 [1.17191424e+16 5.32048241e+11 2.20264658e+04]
 [1.58601345e+15 3.63797095e+42 1.06864746e+13]]


In [34]:
# round / floor / ceil
# round is nearest integer round

np.round(np.random.random((3,4))*100)

# floor is giving you back value like if you have 6.9 so it is become 6 
np.floor(np.random.random((3,4))*100)

# ceil is giving you upword value like if you have 6.5 so it is become 7
np.ceil(np.random.random((3,4))*100)

array([[39., 55., 17., 46.],
       [80., 88., 56., 66.],
       [85., 30., 77., 54.]])

In [35]:
# indexing and slicing
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
a1
# we want to find 8 so 
print(a1[-2])


8


In [37]:
print(a2)
# we can find any number just passing the row and column for that number
print(a2[1,2])
print(a2[2,3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
6
11


In [38]:
print(a3)
print(a3[0,1,1]) #3
print(a3[1,1,0]) #6

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
3
6


In [39]:
# slicing
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
print(a1[2:5])

[2 3 4]


In [41]:
a2
# we want to fetch 1 row

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
a2[0,:]

array([0, 1, 2, 3])

In [44]:
a2[1,:]

array([4, 5, 6, 7])

## **a2[i, :]	entire row i**
## **a2[:, j]	entire column j**
## **a2[i, j]	single element at row i, col j**
## **a2[:, :]	the whole array (all rows, all cols)**

In [45]:
a2[:,1]

array([1, 5, 9])

In [46]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [47]:
a2[0:2,2::]

array([[2, 3],
       [6, 7]])

In [48]:
a2
# want to find 1,3,9,11

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [59]:
a2[1:2,::3]

array([[4, 7]])

In [60]:
a2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [61]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [63]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [68]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [69]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [71]:
# wanna find 2 matrix so
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [73]:
# find 1 and last
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [75]:
a3[0:1,1:2]

array([[[3, 4, 5]]])

In [76]:
a3[1:2,:,1:2]

array([[[10],
        [13],
        [16]]])

In [78]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [80]:
a3[::2,:1,::2]

array([[[ 0,  2]],

       [[18, 20]]])

# Iterating

In [81]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [83]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [86]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [87]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [89]:
for i in np.nditer(a3):
    print(i)

# np.nditer convert the any dimensional array in vector then give you all the values

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping

In [91]:
# Transpose -> makes rows to column , column to rows
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [93]:
# ravel makes every dimension array into 1-d array
np.ravel(a3)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# Stacking
* These functions combine multiple arrays together — the difference is the direction they stack in.
* np.vstack() — Stack Vertically (adds rows, stacks on top of each other)
* np.hstack() — Stack Horizontally (adds columns, side by side)

In [96]:

a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
print(a4)
print(a5)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [97]:
# horizontal stacking
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [98]:
# vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Splitting
* Splitting is the opposite of stacking — instead of combining arrays, you break one array into multiple smaller arrays.
* This splits arr into 3 equal parts. Note the result is a list of arrays, not one array.

In [101]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [102]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [103]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]